version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://nestuser:nestpass@postgres:5432/nestdb
      JWT_SECRET: your_jwt_secret
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
    driver: local