version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://nestuser:nestpass@postgres:5432/nestdb
      JWT_SECRET: your_jwt_secret
    volumes:
      - .:/app
      - /app/node_modules

  prisma:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://nestuser:nestpass@postgres:5432/nestdb
    entrypoint: ["sh", "-c"]
    command: ["npx prisma generate"]

  prisma-studio:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "npm install &&
       npx prisma generate &&
       npx prisma studio --port 5555"
    environment:
      DATABASE_URL: postgres://nestuser:nestpass@postgres:5432/nestdb

volumes:
  pgdata: